---
title: Randomized Complete Block Designs
teaching: 0
exercises: 0
source: Rmd
---

::::::::::::::::::::::::::::::::::::::: objectives

- A randomized complete block design randomizes treatments to experimental units within the block.
- Blocking increases the precision of treatment comparisons.

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::: questions

- What is randomized complete block design?

::::::::::::::::::::::::::::::::::::::::::::::::::

```{r, include=FALSE}
library(tidyverse)
heart_rate <- read_csv("data/simulated_heart_rates.csv")
```

Blocking of experimental units, as presented in an earlier episode on 
[Experimental Design Principles](https://carpentries-incubator.github.io/statistical-experimental-design/design-principles.html#controlling-natural-variation-with-blocking),
can be critical for successful and valuable experiments. Blocking increases
precision in treatment comparisons relative to an unblocked experiment with the
same experimental units. A randomized block design can be thought of as a set
of separate completely randomized designs for comparing the same treatments. 
Each member of the set is a block, and within this block, each of the treatments
is randomly assigned. We can assess treatment differences within each block
and determine whether treatment differences are consistent from block to block.
In other words, we can determine whether there is an interaction block and
treatment.

## Design issues
The first issue to consider in this case is whether or not to block the
experiment. Blocks serve to control natural variation among experimental units,
and randomization within blocks accounts for "nuisance" variables or traits that 
are likely associated with the response. Shelf height and resulting differences
in illumination is one example of a nuisance variable. Age and sex are 
characteristics of experimental units that can influence the treatment response.
Blocking by age and/or sex is a best practice in experimental design.

<!-- In an earlier episode on  -->
<!-- [Completely Randomized Designs](https://carpentries-incubator.github.io/statistical-experimental-design/complete-random-design.html), -->
<!-- we presented the Generation 100 Study of 3 exercise treatments on men and  -->
<!-- women from 70 to 77 years of age. In the actual study, participants were  -->
<!-- stratified (blocked) by sex and cohabitation status (living with someone vs. -->
<!-- living alone) to form 4 blocks. The three treatment levels (control, moderate- -->
<!-- and high-intensity exercise) were randomly assigned within each block. As such, -->
<!-- we would **analyze** the experiment **as designed** in blocks. -->













<!-- Imagine that you want to evaluate the effect of different doses of a new drug on the proliferation of cancer cell lines in vitro. You use -->
<!-- four different cancer cell lines because you would like the results to -->
<!-- generalize to many types of cell lines. Divide each of the cell lines into four -->
<!-- treatment groups, each with the same number of cells. Each treatment group -->
<!-- receives a different dose of the drug for five consecutive days. -->

<!-- Group 1: Control (no drug)   -->
<!-- Group 2: Low dose (10 μM) -->
<!-- Group 3: Medium dose (50 μM) -->
<!-- Group 4: High dose (100 μM) -->

<!-- ```{r} -->

<!-- # create treatment levels -->
<!-- f <- factor(c("control", "low", "medium", "high")) -->

<!-- # create random orderings of the treatment levels -->
<!-- block1 <- sample(f, 4) -->
<!-- block2 <- sample(f, 4) -->
<!-- block3 <- sample(f, 4) -->
<!-- block4 <- sample(f, 4) -->
<!-- treatment <- c(block1, block2, block3, block4) -->
<!-- block <- factor(rep(c("cellLine1", "cellLine2", "cellLine3", "cellLine4"), each = 4)) -->
<!-- dishnum <- rep(1:4, 4) -->
<!-- plan <- data.frame(cellLine = block, DishNumber = dishnum, treatment = treatment) -->
<!-- plan -->
<!-- ``` -->

When analyzing a random complete block design, the effect of the block is
included in the equation along with the effect of the treatment.

## Randomized block design with a single replication

## Sizing a randomized block experiment

## True replication

## Balanced incomplete block designs



:::::::::::::::::::::::::::::::::::::::: keypoints

- Replication, randomization and blocking determine the validity and usefulness of an experiment.

::::::::::::::::::::::::::::::::::::::::::::::::::


